### ISSUE TITLE
Bug Custom Script

### ISSUE THREAD

**Issue by erwinproject** [rtaserver/RakitanManager#43]
<img width="477" alt="image" src="https://github.com/rtaserver/RakitanManager/assets/29509799/df66e66d-8c41-4599-9439-dc6253d6c04e"><br>
- bang di sini ada sedikit typo
- lalu list interface custom script mohon ditambahkan `<input value="">Terminal OpenWRT</input>` biar sama seperti di terminal saat ping
- api untuk modem orbit CPE20 : `curl -d "isTest=false&goformId=REBOOT_DEVICE" -X POST http://192.168.0.1/reqproc/proc_post`

Sekian menyala abangkuh

**Comment by rtaserver** [comment]
mantap mas. saya terapin buat orbitnya
